// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxczlixdprhsdcyfprfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4Y3psaXhkcHJoc2RjeWZwcmZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1ODcwMzgsImV4cCI6MjA3ODE2MzAzOH0.AmOOx2JLqmMdCabiiQzTWS1vC6x9NKSUQ-8IAMr5uzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});